module InvoiceItemsHelper
	def increment_counter
	  if session[:counter].nil?
	  	# it's a hack, we start at 100000 to not clash
	  	# with numbers of the fields generated by fields_for
	    session[:counter] = 100000
	  else
      session[:counter] += 1
	  end
	end

	def counter
		session[:counter].to_s
	end
end
