require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe InvoiceItemsController do

  # This should return the minimal set of attributes required to create a valid
  # InvoiceItem. As you add validations to InvoiceItem, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) { { "price" => "9.99" } }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # InvoiceItemsController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET index" do
    it "assigns all invoice_items as @invoice_items" do
      invoice_item = InvoiceItem.create! valid_attributes
      get :index, {}, valid_session
      assigns(:invoice_items).should eq([invoice_item])
    end
  end

  describe "GET show" do
    it "assigns the requested invoice_item as @invoice_item" do
      invoice_item = InvoiceItem.create! valid_attributes
      get :show, {:id => invoice_item.to_param}, valid_session
      assigns(:invoice_item).should eq(invoice_item)
    end
  end

  describe "GET new" do
    it "assigns a new invoice_item as @invoice_item" do
      get :new, {}, valid_session
      assigns(:invoice_item).should be_a_new(InvoiceItem)
    end
  end

  describe "GET edit" do
    it "assigns the requested invoice_item as @invoice_item" do
      invoice_item = InvoiceItem.create! valid_attributes
      get :edit, {:id => invoice_item.to_param}, valid_session
      assigns(:invoice_item).should eq(invoice_item)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new InvoiceItem" do
        expect {
          post :create, {:invoice_item => valid_attributes}, valid_session
        }.to change(InvoiceItem, :count).by(1)
      end

      it "assigns a newly created invoice_item as @invoice_item" do
        post :create, {:invoice_item => valid_attributes}, valid_session
        assigns(:invoice_item).should be_a(InvoiceItem)
        assigns(:invoice_item).should be_persisted
      end

      it "redirects to the created invoice_item" do
        post :create, {:invoice_item => valid_attributes}, valid_session
        response.should redirect_to(InvoiceItem.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved invoice_item as @invoice_item" do
        # Trigger the behavior that occurs when invalid params are submitted
        InvoiceItem.any_instance.stub(:save).and_return(false)
        post :create, {:invoice_item => { "price" => "invalid value" }}, valid_session
        assigns(:invoice_item).should be_a_new(InvoiceItem)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        InvoiceItem.any_instance.stub(:save).and_return(false)
        post :create, {:invoice_item => { "price" => "invalid value" }}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested invoice_item" do
        invoice_item = InvoiceItem.create! valid_attributes
        # Assuming there are no other invoice_items in the database, this
        # specifies that the InvoiceItem created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        InvoiceItem.any_instance.should_receive(:update).with({ "price" => "9.99" })
        put :update, {:id => invoice_item.to_param, :invoice_item => { "price" => "9.99" }}, valid_session
      end

      it "assigns the requested invoice_item as @invoice_item" do
        invoice_item = InvoiceItem.create! valid_attributes
        put :update, {:id => invoice_item.to_param, :invoice_item => valid_attributes}, valid_session
        assigns(:invoice_item).should eq(invoice_item)
      end

      it "redirects to the invoice_item" do
        invoice_item = InvoiceItem.create! valid_attributes
        put :update, {:id => invoice_item.to_param, :invoice_item => valid_attributes}, valid_session
        response.should redirect_to(invoice_item)
      end
    end

    describe "with invalid params" do
      it "assigns the invoice_item as @invoice_item" do
        invoice_item = InvoiceItem.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        InvoiceItem.any_instance.stub(:save).and_return(false)
        put :update, {:id => invoice_item.to_param, :invoice_item => { "price" => "invalid value" }}, valid_session
        assigns(:invoice_item).should eq(invoice_item)
      end

      it "re-renders the 'edit' template" do
        invoice_item = InvoiceItem.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        InvoiceItem.any_instance.stub(:save).and_return(false)
        put :update, {:id => invoice_item.to_param, :invoice_item => { "price" => "invalid value" }}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested invoice_item" do
      invoice_item = InvoiceItem.create! valid_attributes
      expect {
        delete :destroy, {:id => invoice_item.to_param}, valid_session
      }.to change(InvoiceItem, :count).by(-1)
    end

    it "redirects to the invoice_items list" do
      invoice_item = InvoiceItem.create! valid_attributes
      delete :destroy, {:id => invoice_item.to_param}, valid_session
      response.should redirect_to(invoice_items_url)
    end
  end

end
